mediawiki:
  mediawikiUser: wikiadmin
  mediawikiName: Localhost Wiki
  mediawikiHost: "minikube:30080"
  allowEmptyPassword: "no"

  image:
    registry: ghcr.io
    repository: it-wiki/containers
    tag: main
    pullPolicy: Always

  service:
    type: NodePort
    nodePorts:
      http: "30080"
 